apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crds/takitake_v1alpha1_releasenote_crd.yaml
- role.yaml
- role_binding.yaml
- service_account.yaml
- operator.yaml
- crds/takitake_v1alpha1_releasenote_cr.yaml
configMapGenerator:
- files:
  - cm/template.md
  name: default-template
